#Endpoint para cadastro de usuário
POST http://localhost:8080/api/usuarios
Content-Type: application/json

{
    "email": "ciclano@ciclano",
    "nome": "ciclano",
    "senha": "123456"
}

###

#Endpoint para login no sistema.
POST http://localhost:8080/api/usuarios/login
Content-Type: application/json

{
    "email": "ciclano@ciclano",
    "senha": "123456"
}

